- id: 1
  lot: 1
  points:
  - - 138
    - 210
  - - 160
    - 210
  - - 160
    - 180
  - - 138
    - 180
- id: 2
  lot: 1
  points:
  - - 178
    - 214
  - - 216
    - 214
  - - 216
    - 172
  - - 178
    - 172
- id: 3
  lot: 1
  points:
  - - 226
    - 216
  - - 260
    - 216
  - - 260
    - 175
  - - 226
    - 175
- id: 4
  lot: 1
  points:
  - - 272
    - 213
  - - 316
    - 213
  - - 316
    - 178
  - - 272
    - 178
- id: 5
  lot: 1
  points:
  - - 282
    - 275
  - - 336
    - 275
  - - 336
    - 230
  - - 282
    - 230
- id: 6
  lot: 1
  points:
  - - 236
    - 280
  - - 266
    - 280
  - - 266
    - 224
  - - 236
    - 224
- id: 7
  lot: 1
  points:
  - - 177
    - 277
  - - 210
    - 277
  - - 210
    - 228
  - - 177
    - 228
- id: 8
  lot: 1
  points:
  - - 118
    - 277
  - - 140
    - 277
  - - 140
    - 224
  - - 118
    - 224
- id: 9
  lot: 1
  points:
  - - 74
    - 268
  - - 88
    - 268
  - - 88
    - 227
  - - 74
    - 227
- id: 10
  lot: 1
  points:
  - - 96
    - 203
  - - 112
    - 203
  - - 112
    - 169
  - - 96
    - 169
